source 'https://rubygems.org'

# frozen_string_literal: true

gem 'allure-cucumber'
gem 'appium_console'
gem 'appium_lib'
gem 'cucumber'
gem 'capybara'
gem 'pry'
gem 'rake'
gem 'selenium-webdriver'
gem 'rspec'
gem 'eventmachine'
gem 'rest-client'