# frozen_string_literal: true

require 'cucumber'
require 'cucumber/rake/task'

desc 'Testes com android local'
task :android_local,:tags do |t, args|
    sh "bundle exec cucumber -p android_local -t #{args[:tags]}"
end

desc 'Testes com iOS local'
task :ios_local,:tags do |t, args|
    sh "bundle exec cucumber -p ios_local -t #{args[:tags]}"
end

desc 'Testes com android farm'
task :android_farm,:tags do |t, args|
    sh "bundle exec cucumber -p android_farm -t #{args[:tags]}"
end

desc 'Testes com iOS farm'
task :ios_farm,:tags do |t, args|
    sh "bundle exec cucumber -p ios_farm -t #{args[:tags]}"
end





